### ISSUE TITLE
Table in the Compute Window is not adapted to the table frame

### ISSUE THREAD

**Issue by benjamingoll99** [GVigne/Molonari-2022#33]
Scroll bar seems not the good choice here ? There are only 5 columns and 3 lines...

**Comment by Jia-FU-Soline** [comment]
Plus précisément? J'ai pas bien compris. Mais en fait on a besoin un scroll bar à un moment parce que le nombre de layers change entre 1-10

**Comment by fabien-ors** [comment]
Fixed
